CREATE TABLE IF NOT EXISTS llm_providers (
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  providerName VARCHAR(128) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  hidden TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS llm_models (
  id MEDIUMINT UNSIGNED AUTO_INCREMENT,
  modelName VARCHAR(64) NOT NULL,
  modelApiName VARCHAR(128) NOT NULL,
  providerId MEDIUMINT UNSIGNED NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  hidden TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  CONSTRAINT fk_provider FOREIGN KEY (providerId) REFERENCES llm_providers(id) ON DELETE CASCADE
) ENGINE=InnoDB;
