CREATE TABLE IF NOT EXISTS tools (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tool_name VARCHAR(128) NOT NULL,
  tool_slug VARCHAR(64) NOT NULL,
  description TEXT NULL,
  input_schema JSON NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB;
