CREATE TABLE IF NOT EXISTS tools (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  toolName VARCHAR(128) NOT NULL,
  toolClass VARCHAR(64) NOT NULL,
  description TEXT NULL,
  active TINYINT(1) NOT NULL DEFAULT 0,
  checksum CHAR(64) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY ux_tools_checksum (checksum)
) ENGINE=InnoDB;
