CREATE TABLE IF NOT EXISTS agents (
    id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id MEDIUMINT UNSIGNED NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS agent_versions (
    id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id MEDIUMINT UNSIGNED NOT NULL,
    agent_id MEDIUMINT UNSIGNED NOT NULL,
    version INT NOT NULL,
    live TINYINT(1) NOT NULL DEFAULT 0,
    locked TINYINT(1) NOT NULL DEFAULT 0,
    prompt LONGTEXT NOT NULL,
    llm_provider_id MEDIUMINT UNSIGNED NOT NULL,
    llm_model_id MEDIUMINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_agent FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
    CONSTRAINT fk_llm_provider FOREIGN KEY (llm_provider_id) REFERENCES llm_providers(id) ON DELETE CASCADE,
    CONSTRAINT fk_llm_model FOREIGN KEY (llm_model_id) REFERENCES llm_models(id) ON DELETE CASCADE,
    UNIQUE KEY unique_agent_version (agent_id, version)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS agent_tools (
    id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
    agent_version_id MEDIUMINT UNSIGNED NOT NULL,
    tool_id SMALLINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_agent_version FOREIGN KEY (agent_version_id) REFERENCES agent_versions(id) ON DELETE CASCADE,
    CONSTRAINT fk_tool FOREIGN KEY (tool_id) REFERENCES tools(id) ON DELETE CASCADE,
    UNIQUE KEY unique_agent_tool (agent_version_id, tool_id)
) ENGINE=InnoDB;
