CREATE TABLE IF NOT EXISTS agents (
    id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
    userId MEDIUMINT UNSIGNED NOT NULL,
    name VARCHAR(255) NOT NULL,
    prompt LONGTEXT NULL,
    providerId MEDIUMINT UNSIGNED NULL,
    modelId MEDIUMINT UNSIGNED NULL,
    description TEXT NULL,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    deletedAt DATETIME NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_llm_provider FOREIGN KEY (providerId) REFERENCES llm_providers(id) ON DELETE SET NULL,
    CONSTRAINT fk_llm_model FOREIGN KEY (modelId) REFERENCES llm_models(id) ON DELETE SET NULL,
    CONSTRAINT fk_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS agent_tools (
    id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
    userId MEDIUMINT UNSIGNED NOT NULL,
    agentId MEDIUMINT UNSIGNED NOT NULL,
    toolId SMALLINT UNSIGNED NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY ux_agent_tool (agentId, toolId),
    CONSTRAINT fk_agent FOREIGN KEY (agentId) REFERENCES agents(id) ON DELETE CASCADE,
    CONSTRAINT fk_tool FOREIGN KEY (toolId) REFERENCES tools(id) ON DELETE CASCADE,
    CONSTRAINT fk_tool_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
